### ISSUE TITLE
ddos-guard for purr-hollands, MuziekFabriek and Film-Paleis no longer being detected

### ISSUE THREAD

**Issue by garfield69** [FlareSolverr/FlareSolverrSharp#7]
The other ddos-guard for EbookParadijs is still being detected but Puur-Hollands, MuziekFabriek and Film-Paleis no longer works
```HMTL
Error on 20220311170740 for Puur-Hollands.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.puur-hollands.org/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1504




 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>DDoS protection | Puur-Hollands.org</title>
<style type="text/css">
    .main_t {height: 100%; width: 100%; border: 0px solid black;}
    .main_t td {text-align: center;}
    .main_t td.info {height: 100%; text-align: center; vertical-align: top; padding-top: 5em;}
	
    .sign { color: #ccc; margin-top: 5em;}
    .sign a { color: #ccc; }
</style>
<script>
function get_current_url() {
    document.write(window.location.href);
    return null;
}
</script>
</head>
<body>
    <table class="main_t">
        <tr>
            <td class="info">
                <h1>DDoS protection actief voor ip <a href="/blacklists/2407:7000:9bc1:4100:f17c:ed10:6b08:f37c" target="_new">2407:7000:9bc1:4100:f17c:ed10:6b08:f37c</a></h1>
                <p>Duurt het laden erg lang, klik op de link om door te gaan.</p>
                <a href=''><script>get_current_url();</script></a>


                <p>U word automatisch doorgestuurd na de juiste pagina over 3 seconds.</p>
                <div id="js_info">
                    <p>Zorg dat u Cookies en JavaScript heeft ingeschakeld, anders kunt u niet aanmelden.</p>
                </div>
            </td>
        </tr>
        <tr>
            <td class="sign"><span style="color: #49C73B;">
                   DDoS protection by </span><span style="color: #49C73B;">Puur-Hollands</span><span style="color: #349EBF;">.org</span><br />

        <noscript>Please enable Javascript to see the requested page.</noscript>
            </td>
        </tr>
    </table>
    <script type="text/javascript">
        document.getElementById('js_info').style.display = 'none';
        var date = new Date();

        days = '180';
        date.setTime(date.getTime() + (days * 24*60*60*1000));

        document.cookie = 'ct_anti_ddos_key' + "=" + escape('db56d634f6beab33862a96fb9cf53f84') + "; expires = " + date.toGMTString() + "; path=/";
        setTimeout(function(){
           window.location.reload(1);
        }, 3000);
    </script>
</body>
</html>
```

no idea why.
[edit] 3rd edit. as time goes by the other sites are also switching to the newly changed ddos-guard and jackett's flaresolverr is failing to handle them.

**Comment by garfield69** [comment]
working again now %-/
